ACCREDITATION & LICENSING - ARGZERO PROJECT LICENSE (noncommercial)
[NOTE THAT THE LICENSE USED IN THIS SOFTWARE AND ITS TERMS ARE LIABLE TO CHANGE AND IT IS YOUR RESPONSIBILITY AS A USER OF THIS SOFTWARE TO TAKE NOTE OF THOSE CHANGES. BY USING, MODIFYING, OR INCORPORATING THIS PROJECT INTO YOUR OWN WORK, YOU INDICATE THAT YOU AGREE TO THESE TERMS; TO CEASE FOLLOWING THE AGREEMENT, CEASE ALL USE OF THE SOFTWARE OR ITS VARIOUS PARTS IN ALL PROJECTS. IF YOU HAVE THIS SOFTWARE IN ANY PROJECT THIS AGREEMENT, INCLUDING ALL APPLICABLE TERMS, STILL STANDS.]

IF AT ANY POINT ARGZERO IS USED AS A TITLE IN THIS DOCUMENT, IT MAY BE INTERCHANGED WITH FORREST ZACHARY SHOOSTER. ESSENTIALLY, IF IT APPLIES TO ARGZERO, IT ALSO APPLIES TO FORREST ZACHARY SHOOSTER (this implies that you may use either name to give credit). In the event that an Argzero project becomes an Argzero Technologies, LLC project, you are required to use the business name Argzero Technologies, LLC to give credit for use. This is not true if you used the project before this change occurred and instead you may use Argzero or Forrest Zachary Shooster to give credit. Please note that the readme in the repository containing this notice also contains rules you must follow with regards to this repository. By in any way making use of, reviewing, creating derivatives of, or otherwise interacting with this project beyond its GitHub top level page, readme, and this notice, you agree to the terms found herein.

To use the Argzero Technologies, LLC project in this repo (APR), You must give credit to Argzero Technologies, LLC for use. Otherwise, you may feel free to modify the code or use it in other noncommercial projects, however know that in modifying the code for your purposes you should (MUST) notify Argzero of your use of APR at his email at forrest@argzero.org. If Argzero is already aware of your use of his project, you are excluded from the requirement of notifying him of your use of the project. For a commercial use license, please contact Argzero Technologies, LLC via the email above or via the website contact form found at https://argzero.org/tech/.

Additionally, Argzero does humbly request that you notify him of any improvements you have come up with for his APR so that he may continue to provide quality APR in the future both for your sake and his.

Argzero is available to help you with your integration of this upon request. Please send all requests to his email as stated in the above paragraph. Currently this is a free service available to any who request it. By agreeing to these terms, you acknowledge that Argzero has the right to deny you this service if he so chooses. In use of or integration of any content of APR including but not limited to source code, assets, or other materials provided by Argzero, you both acknowledge that you are aware of and agree to these terms. 

You can probably expect a response within 2-7 business days. If not, post an issue here stating that he has not responded to you. It is quite possible that Argzero's email provider labeled your message as spam. If you would like Argzero’s undivided attention and you have a deadline to meet or other special circumstances, feel free to contact him regarding payments for contract work or other form of employment by his email at forrest@argzero.org. If you need to reach Argzero for an emergency ONLY, contact him at his personal email at forrest.z.shooster@gmail.com.
